stages:
  - build
  - test

before_script:
  - python --version
  - pip install --upgrade pip

build:
  stage: build
  image: python:3.11
  script:
    - echo "Building project..."
    - pip install -r requirements.txt  # si tu as un fichier requirements.txt

test:
  stage: test
  image: python:3.11
  script:
    - echo "Running tests with pytest..."
    - pip install pytest
    - pytest -v
